Feature/eurlex metadata
ModelOriented/AI-strategies-papers-regulations-monitoring pull request #34
Opened 2021-10-28 14:45 UTC by HaZdula

2021-11-02 07:52 UTC, Gizzio requested changes

2021-11-02 07:52 UTC, Gizzio commented on scripts/eurlex-metadata-scraping.py
> +        if not doc[db_fields.TITLE]:
Czemu tutaj filtrujemy po braku tytułu? Lepiej na poziomie bazki {db.fields.TITLE: None}

2021-11-03 20:55 UTC, piotrpiatyszek requested changes

2021-11-03 20:55 UTC, piotrpiatyszek commented on scripts/eurlex-metadata-scraping.py
> +    {db_fields.SOURCE: db_fields.SourceWebsite.eurlex}, batchSize=1000
Gdy w bazie będzie więcej niż 1000 dokumentów, to ta pętla się wysypie, bo pobranie wszystkich wyników z bazy musi trwać < 30s. Najłatwiej pobrać wszystko za jednym razem. Skoro to tylko url, to raczej ramu nie zabraknie.
```
for doc in list(collections.document_sources.fetchByExample {db_fields.SOURCE: db_fields.SourceWebsite.eurlex}, batchSize=1000)):
```

2021-11-03 20:55 UTC, piotrpiatyszek commented on scripts/eurlex-metadata-scraping.py
> +        logging.log_exception("", e, logger)
Bardzo dobrze by było wypisać do błędów url i id dokumentu. Ułatwiło by to ewentualne późniejsze debugowanie.

2021-11-05 13:15 UTC, piotrpiatyszek approved these changes

2021-11-07 12:57 UTC, merged