Similarities calculator, removed unused functions
ModelOriented/AI-strategies-papers-regulations-monitoring pull request #41
Opened 2021-12-01 15:46 UTC by Gizzio

2021-12-03 01:27 UTC, piotrpiatyszek requested changes
Biblioteka się instaluje w trakcie działania kodu. Dodajcie ją do poetry. `en-core-web-md`

2021-12-03 01:44 UTC, piotrpiatyszek commented on mars/keyword_topic_model.py
> +import spacy
W tym pliku spacy nie jest używane

2021-12-03 01:49 UTC, piotrpiatyszek commented on mars/similarity_calculation.py
Funkcja calculate_similarities_to_targets powinna być usunięta, bo bazuje na nieaktualnej strukturze bazy.

2021-12-03 09:54 UTC, jakwisn commented on mars/keyword_topic_model.py
> +import spacy
jest używane w linijkach 11 i 14

2021-12-06 13:47 UTC, jakwisn commented on mars/similarity_calculation.py
> +    ) / 2
@Gizzio zrobisz do tego jakiś test? Nie musi być teraz, ale generalnie to chyba ważny komponent i warto testować żeby się nie wykrzaczył

2021-12-06 15:32 UTC, piotrpiatyszek commented
Na obecnym etapie wszystko działa i kod jest relatywnie ok.Testy by się oczywiście przydały, ale już nie w tym pullu.

2021-12-06 15:41 UTC, merged